"use strict";
Object.defineProperty(exports, "__esModule", { value: true });
const main_1 = require("./main");
const owner = new main_1.TS.VehicleOwner('Володько', 'Ксения', 'Евгеньевна', new Date('2005-12-28'), main_1.TS.DocType.PASSPORT, '7777', '777777');
const vehicle1 = new main_1.TS.Transport('GAZ', 'Volga 23', 1962, 'ABC123', "1437", owner);
vehicle1.displayVehicle();
owner.displayOwner();
console.log("///////////////");
const carOwner = new main_1.TS.VehicleOwner('Володько', 'Ксения', 'Евгеньевна', new Date('2004-02-01'), main_1.TS.DocType.PASSPORT, '7777', '777777');
const car = new main_1.TS.Car('GAZ', 'Volga 23', 1962, 'ABC123', "1437", carOwner, main_1.TS.BodyType.SEDAN, main_1.TS.CarClass.HIGHEND);
car.displayVehicle();
carOwner.displayOwner();
console.log("///////////////");
const motoOwner = new main_1.TS.VehicleOwner('Володько', 'Ксения', 'Евгеньевна', new Date('2004-02-01'), main_1.TS.DocType.PASSPORT, '7777', '777777');
const motorbike = new main_1.TS.Motorcycle('Honda', 'CBR1000RR', 2023, 'XYZ789', '1437', motoOwner, 'Спортивная', true);
motorbike.displayVehicle();
motoOwner.displayOwner();
console.log("///////////////");
const carStorage = new main_1.TS.Garage(new Date('1987-01-01'), [car]);
const allCars = carStorage.displayVehicles();
console.log(allCars);
